version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go:
        patterns: ["*"]

  - package-ecosystem: gomod
    directory: /backends/s3
    schedule:
      interval: weekly
    groups:
      aws:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      frontend:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /e2e
    schedule:
      interval: weekly
    groups:
      e2e:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
